### ISSUE TITLE
Add possibility to copy only on start

### ISSUE THREAD

**Issue by vladshcherbin** [eritikass/rollup-copy-plugin#1]
It would be nice to have an option to copy on start or on write. It's useful in watch mode when you don't want to copy files every time you bundle changes. The option can be named `watch` or smth.

**Comment by eritikass** [comment]
Nice idea ... as rollup will not watch those files anyway for changes so those later copies would be just wasting of io. Made so (#3) that now it only copies once for startup and ignores later.

released as `0.1.0`

**Comment by vladshcherbin** [comment]
@eritikass very nice, thank you 😉
